---

  - name: add ondrej's php ppa
    when: (ansible_distribution == "Ubuntu" or ansible_distribution == "Debian")
    apt_repository:
      repo: 'ppa:ondrej/php'
      state: present
      update_cache: True


  - name: update cache
    when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
    apt: update_cache=yes
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2

  - name: update system
    when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
    apt: upgrade=dist
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2
