---

  - name: install packages
    when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
    apt:
      name:
        - 'nginx'
        - 'ffmpeg'
        - 'memcached'
        - 'redis-server'
        - 'libmemcached-tools'
        - 'php8.3'
        - 'php8.3-common'
        - 'php8.3-curl'
        - 'php8.3-mysql'
        - 'php8.3-fpm'
        - 'php8.3-cli'
        - 'php8.3-gd'
        - 'php8.3-imagick'
        - 'php8.3-intl'
        - 'php8.3-exif'
        - 'php8.3-json'
        - 'php8.3-mbstring'
        - 'php8.3-memcached'
        - 'php8.3-readline'
        - 'php8.3-redis'
        - 'php8.3-xml'
        - 'php8.3-zip'
        - 'php8.3-bz2'
        - 'python3-pip'
        - 'mysql-server'
        - 'mysql-client'
        - 'libmysqlclient-dev'
        - 'python3-mysqldb'
        - 'unzip'
        - 'ufw'

      state: present

    register: task_result
    until: task_result is success 
    retries: 10
    delay: 2


  - name: install certbot
    when: (leEmail is defined and ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")
    apt:
      name: certbot
      state: present
    register: task_result
    until: task_result is success
    retries: 10
    delay: 2
